/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkTownTalkRouteImport } from './routes/work.town-talk'
import { Route as WorkStrongerTogetherRouteImport } from './routes/work.stronger-together'
import { Route as WorkPaideiaGoogleRouteImport } from './routes/work.paideia-google'
import { Route as WorkLittlePalmerhausRouteImport } from './routes/work.little-palmerhaus'
import { Route as WorkGuruKreatorRouteImport } from './routes/work.guru-kreator'
import { Route as WorkGrabMerchantRouteImport } from './routes/work.grab-merchant'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkTownTalkRoute = WorkTownTalkRouteImport.update({
  id: '/work/town-talk',
  path: '/work/town-talk',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkStrongerTogetherRoute = WorkStrongerTogetherRouteImport.update({
  id: '/work/stronger-together',
  path: '/work/stronger-together',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkPaideiaGoogleRoute = WorkPaideiaGoogleRouteImport.update({
  id: '/work/paideia-google',
  path: '/work/paideia-google',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkLittlePalmerhausRoute = WorkLittlePalmerhausRouteImport.update({
  id: '/work/little-palmerhaus',
  path: '/work/little-palmerhaus',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkGuruKreatorRoute = WorkGuruKreatorRouteImport.update({
  id: '/work/guru-kreator',
  path: '/work/guru-kreator',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkGrabMerchantRoute = WorkGrabMerchantRouteImport.update({
  id: '/work/grab-merchant',
  path: '/work/grab-merchant',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/work/grab-merchant': typeof WorkGrabMerchantRoute
  '/work/guru-kreator': typeof WorkGuruKreatorRoute
  '/work/little-palmerhaus': typeof WorkLittlePalmerhausRoute
  '/work/paideia-google': typeof WorkPaideiaGoogleRoute
  '/work/stronger-together': typeof WorkStrongerTogetherRoute
  '/work/town-talk': typeof WorkTownTalkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/work/grab-merchant': typeof WorkGrabMerchantRoute
  '/work/guru-kreator': typeof WorkGuruKreatorRoute
  '/work/little-palmerhaus': typeof WorkLittlePalmerhausRoute
  '/work/paideia-google': typeof WorkPaideiaGoogleRoute
  '/work/stronger-together': typeof WorkStrongerTogetherRoute
  '/work/town-talk': typeof WorkTownTalkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/work/grab-merchant': typeof WorkGrabMerchantRoute
  '/work/guru-kreator': typeof WorkGuruKreatorRoute
  '/work/little-palmerhaus': typeof WorkLittlePalmerhausRoute
  '/work/paideia-google': typeof WorkPaideiaGoogleRoute
  '/work/stronger-together': typeof WorkStrongerTogetherRoute
  '/work/town-talk': typeof WorkTownTalkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/work/grab-merchant'
    | '/work/guru-kreator'
    | '/work/little-palmerhaus'
    | '/work/paideia-google'
    | '/work/stronger-together'
    | '/work/town-talk'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/work/grab-merchant'
    | '/work/guru-kreator'
    | '/work/little-palmerhaus'
    | '/work/paideia-google'
    | '/work/stronger-together'
    | '/work/town-talk'
  id:
    | '__root__'
    | '/'
    | '/work/grab-merchant'
    | '/work/guru-kreator'
    | '/work/little-palmerhaus'
    | '/work/paideia-google'
    | '/work/stronger-together'
    | '/work/town-talk'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkGrabMerchantRoute: typeof WorkGrabMerchantRoute
  WorkGuruKreatorRoute: typeof WorkGuruKreatorRoute
  WorkLittlePalmerhausRoute: typeof WorkLittlePalmerhausRoute
  WorkPaideiaGoogleRoute: typeof WorkPaideiaGoogleRoute
  WorkStrongerTogetherRoute: typeof WorkStrongerTogetherRoute
  WorkTownTalkRoute: typeof WorkTownTalkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/town-talk': {
      id: '/work/town-talk'
      path: '/work/town-talk'
      fullPath: '/work/town-talk'
      preLoaderRoute: typeof WorkTownTalkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/stronger-together': {
      id: '/work/stronger-together'
      path: '/work/stronger-together'
      fullPath: '/work/stronger-together'
      preLoaderRoute: typeof WorkStrongerTogetherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/paideia-google': {
      id: '/work/paideia-google'
      path: '/work/paideia-google'
      fullPath: '/work/paideia-google'
      preLoaderRoute: typeof WorkPaideiaGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/little-palmerhaus': {
      id: '/work/little-palmerhaus'
      path: '/work/little-palmerhaus'
      fullPath: '/work/little-palmerhaus'
      preLoaderRoute: typeof WorkLittlePalmerhausRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/guru-kreator': {
      id: '/work/guru-kreator'
      path: '/work/guru-kreator'
      fullPath: '/work/guru-kreator'
      preLoaderRoute: typeof WorkGuruKreatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/grab-merchant': {
      id: '/work/grab-merchant'
      path: '/work/grab-merchant'
      fullPath: '/work/grab-merchant'
      preLoaderRoute: typeof WorkGrabMerchantRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkGrabMerchantRoute: WorkGrabMerchantRoute,
  WorkGuruKreatorRoute: WorkGuruKreatorRoute,
  WorkLittlePalmerhausRoute: WorkLittlePalmerhausRoute,
  WorkPaideiaGoogleRoute: WorkPaideiaGoogleRoute,
  WorkStrongerTogetherRoute: WorkStrongerTogetherRoute,
  WorkTownTalkRoute: WorkTownTalkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
